

server:
  port: 8090
  contextPath: /mercury

spring:
  profile:
    active: local

    
---    
spring:
  profiles: test
  main:
    banner-mode: "off"
datasource:
  mercury:
    # url: jdbc:h2:~/test
    url: jdbc:h2:file:/tmp/test;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect 
---
spring:
  profiles: dev,prod
  main:
    banner-mode: "off"
  jpa:
    properties:
      show_sql: true
    hibernate:
      ddl-auto: create
      hbm2ddl.method: create
      show_sql: true
      format_sql: true
datasource:
  mercury:
    url: jdbc:mariadb://localhost:3306/mercury
    username: mercury
    password: mercury
    driverClassName: org.mariadb.jdbc.Driver
    defaultSchema: mercury
    maxPoolSize: 10
