
spring.jmx:
  enabled: false

server:
  port: 8090
  contextPath: /mercury

spring:
  main:
    banner-mode: "off"
  data:
    rest:
      base-path: /data

security:
  basic:
    enabled: false
management:
  security:
    enabled: false

---    
spring:
  profiles: test

  jpa:
    generate-ddl: true
    properties:
      show_sql: true
    hibernate:
      ddl-auto: create-drop

datasource:
  mercury:
    # url: jdbc:h2:~/test
    url: jdbc:h2:file:/tmp/test;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10

---
spring:
  profiles: dev,prod

  jpa:
    generate-ddl: true
    properties:
      show_sql: true
    hibernate:
      ddl-auto: create-drop

datasource:
  mercury:
    url: jdbc:mariadb://localhost:3306/mercury
    username: mercury
    password: mercury
    driverClassName: org.mariadb.jdbc.Driver
    defaultSchema: mercury
    maxPoolSize: 10
